config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)" do
    get "help", to: "static_pages#help"
    devise_for :users
    resources :transfers do
      collection do
        post :fee
      end
    end
    resources :senders
    resources :recipients
    namespace :admin do
      resources :exchanges
      resources :transfers do
        collection do
          post :fee
        end
      end
      resources :high_transfers, only: %i[new create]
    end
  end
end

app/models/exchange.rb
# == Schema Information
#
# Table name: exchanges
#
#  created_at       :datetime         not null
#  currency_from_id :integer
#  currency_to_id   :integer
#  guaranteed_rate  :float
#  id               :integer          not null, primary key
#  updated_at       :datetime         not null
#

# Exchange
class Exchange < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :currency_from, class_name: "M::Currency",
    foreign_key: "currency_from_id"
  belongs_to_active_hash :currency_to, class_name: "M::Currency",
    foreign_key: "currency_to_id"
end

app/models/m/exchange.rb
# Exchange
class M::Exchange < ActiveHash::Base
  self.data = [
    { id: 1, name: "中国銀行為替", guaranteed_rate_from_jpy: 0.05953,
      guaranteed_rate_from_cny: 16.85 },
    { id: 2, name: "銀聯為替", guaranteed_rate_from_jpy: 0.05952,
      guaranteed_rate_from_cny: 16.83 },
    { id: 3, name: "アリペイ", guaranteed_rate_from_jpy: 0.0595,
      guaranteed_rate_from_cny: 16.84 },
    { id: 4, name: "Yahoo Japan", guaranteed_rate_from_jpy:
      0.0591, guaranteed_rate_from_cny: 16.93 }
  ]
end

app/controllers/admin/exchanges_controller.rb
# exchange
class Admin::ExchangesController < Admin::BaseController
  before_action :set_exchange, only: %i[edit update]
  def index
    @bank_exchanges = BankExchange.order jp_name: :desc, currency_from_id: :asc
    @uneeds_exchanges = UneedsExchange.order :currency_from_id
  end

  def edit
  end

  def update
    if @exchange.update(exchange_params)
      flash[:notice] = t ".success"
      redirect_to admin_exchanges_path
    else
      render :edit
    end
  end

  private

  def set_exchange
    @exchange = Exchange.find params[:id]
  end

  def exchange_params
    params.require(:exchange).permit(:jp_name, :cn_name, :guaranteed_rate)
  end
end

app/views/admin/exchanges/_bank_exchanges.html.slim
.panel.panel-default
  .panel-heading
    h4 = t ".bank_exchange"
  .panel-body
    .table-responsive
      table.table.table-striped
        thead
          tr
            th.text-center = t ".num_order"
            th = t ".bank_jp_name"
            th = t ".bank_cn_name"
            th = t ".currency_from"
            th = t ".currency_to"
            th = t ".guaranteed_rate"
            th.text-center = t ".action"

        tbody
          = render partial: "exchange", collection: bank_exchanges

app/views/admin/exchanges/_exchange.html.slim
tr
  td.text-center
    = exchange_counter + 1
  td
    = exchange.jp_name
  td
    = exchange.cn_name
  td
    div class="#{exchange.currency_from.name.downcase}"
  td
    div class="#{exchange.currency_to.name.downcase}"
  td
    = exchange.guaranteed_rate
  td.text-center
    .btn-group.navbar-btn
      = link_to t(".edit"), edit_admin_exchange_path(exchange), class: "btn btn-info"

app/views/admin/exchanges/_form.html.slim
= simple_form_for :exchange, url: admin_exchange_path, method:"PUT" do |f|
  .panel.panel-default
    .panel-heading
      = t ".#{exchange.code.downcase}"
    .panel-body
      = f.input :jp_name, label: t(".jp_name")
      = f.input :cn_name, label: t(".cn_name")
      = f.input :guaranteed_rate, label: t(".guaranteed_rate")
  .col-lg-12.text-center
    = f.submit  t(".update"), class: 'btn btn-primary'

app/views/admin/exchanges/_uneeds_exchanges.html.slim
.panel.panel-default
  .panel-heading
    h4 = t ".uneeds_exchange"
  .panel-body
    .table-responsive
      table.table.table-striped
        thead
          tr
            th.text-center = t ".num_order"
            th = t ".jp_name"
            th = t ".cn_name"
            th = t ".currency_from"
            th = t ".currency_to"
            th = t ".guaranteed_rate"
            th.text-center = t ".action"

        tbody
          = render partial: "exchange", collection: uneeds_exchanges

app/views/admin/exchanges/edit.html.slim
- provide :title, t(".title")
= link_to t(".back"), admin_exchanges_path
= render "form", exchange: @exchange

app/views/admin/exchanges/index.html.slim
- provide :title, t(".title")
.content
  .block
    .block-content
      .row
        .col-xs-9
        .col-xs-3
      = render "uneeds_exchanges", uneeds_exchanges: @uneeds_exchanges
      = render "bank_exchanges", bank_exchanges: @bank_exchanges