config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)" do
    get "help", to: "static_pages#help"
    devise_for :users
    resources :transfers do
      collection do
        post :fee
      end
    end
    resources :senders
    resources :recipients
    namespace :admin do
      resources :exchanges
      resources :transfers do
        collection do
          post :fee
        end
      end
      resources :high_transfers, only: %i[new create]
    end
  end
end

app/views/shared/_cny_ensign.html.slim
.ensign.cny data = data

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© <%= t(".company_info")%> <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_jpy_ensign.html.slim
.ensign.jpy data = data

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Uneeds", root_path, :class => "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%= navbar_link_to t(".home"), root_path,
          active_when: { controller: "home" } %>
        <% case %>
        <% when admin? %>
          <%= navbar_link_to t(".exchanges_management"), admin_exchanges_path,
            active_when: { controller: "admin/exchanges" } %>
          <%= navbar_link_to t(".transfers_management"), admin_transfers_path,
            active_when: { controller: "admin/transfers", action: "index" }%>
          <%= navbar_link_to t(".add_high_transfer"), new_admin_high_transfer_path,
            active_when: { controller: "admin/high_transfers", action: /new|create/ }%>
        <% when normal_user? %>
          <%= navbar_link_to t(".sender_list"), senders_path,
            active_when: {controller: "senders", action: "index"} %>
          <%= navbar_link_to t(".recipient_list"), recipients_path,
            active_when: {controller: "recipients", action: "index"} %>
          <%= navbar_link_to t(".transfer_list"), transfers_path,
            active_when: {controller: "transfers", action: "index"} %>
          <%= navbar_link_to t(".help"), help_path,
            active_when: {controller: "static_pages", action: "help"} %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to image_tag("ensigns/jpy.png", width: 24, height: 24), {locale: "ja"} %>
        </li>
        <li>
          <%= link_to image_tag("ensigns/cny.png", width: 24, height: 24), {locale: "zh-CN"} %>
        </li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= t ".settings" %></a></li>
              <li><%= link_to t(".log_out"), destroy_user_session_path, method: :delete %></li>
            </ul>
        <% else %>
          <li><%= link_to t(".log_in"), new_user_session_path %></li>
          <li><%= link_to t(".register"), new_user_registration_path %></a></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% else %>
    <h1>Untitled</h1>
    <p>Don’t forget to set <code>provide(:title)</code> for this view!</p>
  <% end %>
</div>