config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)" do
    get "help", to: "static_pages#help"
    devise_for :users
    resources :transfers do
      collection do
        post :fee
      end
    end
    resources :senders
    resources :recipients
    namespace :admin do
      resources :exchanges
      resources :transfers do
        collection do
          post :fee
        end
      end
      resources :high_transfers, only: %i[new create]
    end
  end
end

app/models/recipient.rb
# == Schema Information
#
# Table name: recipients
#
#  account_number :string
#  account_type   :integer
#  bank_name      :string
#  branch_name    :string
#  created_at     :datetime         not null
#  currency       :integer
#  email          :string
#  full_name      :string
#  id             :integer          not null, primary key
#  kind           :string
#  updated_at     :datetime         not null
#  user_id        :integer
#
# Indexes
#
#  index_recipients_on_user_id  (user_id)
#

# Recipient
class Recipient < ApplicationRecord
  belongs_to :user
  has_many :transfers, dependent: :nullify

  validates :account_number, :bank_name, :branch_name, :full_name,
            :currency, presence: true

  validates :account_type, presence: true, if: :cny_to_jpy?

  enum account_type: %i[futsuu chochiku touza]
  enum currency: %i[jpy cny]

  PERMITTED_ATTRIBUTES = %i[
    full_name email account_number account_type bank_name branch_name
  ].freeze

  private

  def from_japan?
    transfer.payment.uneeds_exchange.currency_from_id == 1
  end

  def from_china?
    transfer.payment.uneeds_exchange.currency_from_id == 2
  end

  def cny_to_jpy?
    # return false unless below_kind?
    jpy?
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def index
    @recipients = current_user.recipients.decorate
  end

  def edit
    recipient
  end

  def update
    if recipient.update_attributes recipient_params
      flash.notice = t ".success"
      redirect_to recipients_path
    else
      render :edit
    end
  end

  def destroy
    if recipient.destroy
      flash[:notice] = t ".success"
    else
      flash[:alert] = t ".failure"
    end
    redirect_to recipients_path
  end

  private

  def recipient
    @recipient = Recipient.find params[:id]
  end

  def recipient_params
    params.require(:recipient).permit Recipient::PERMITTED_ATTRIBUTES
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
  def account_type_options
    Recipient.account_types.keys.map do |account_type|
      [I18n.t("dictionary.account_types.#{account_type}"), account_type]
    end
  end

  def currency_options
    Recipient.currencies.keys.map do |currency|
      [I18n.t("dictionary.currencies.#{currency}"), currency]
    end
  end
end

app/views/recipients/_form.html.slim
= simple_form_for recipient do |f|
  .panel.panel-default
    .panel-heading
      = t ".recipient_info"
    .panel-body
      = f.input :email, label: t(".email")
      = f.input :bank_name, label: t(".bank_name")
      = f.input :branch_name, label: t(".branch_name")
      = f.input :account_number, label: t(".account_number")
      = f.input :account_type, collection: account_type_options,
        prompt: t(".choose_account_type"), label: t(".account_type")
      = f.input :full_name, label: t(".recipent_name")
      = f.input :currency, disabled: true, collection: currency_options,
        prompt: t(".choose_currency"), label: t(".currency")
  .col-lg-12.text-center
    = f.submit  t(".update"), class: "btn btn-primary"

app/views/recipients/_recipient.html.slim
tr
  td
    = recipient.email
  td
    = recipient.bank_name
  td
    = recipient.branch_name
  td
    = recipient.decorated_account_type
  td
    = recipient.account_number
  td
    = recipient.full_name
  td
    = recipient.decorated_currency
  td.text-center
    .btn-group.navbar-btn
      = link_to t(".edit"), edit_recipient_path(recipient), class: "btn btn-info"
    .btn-group.navbar-btn.ml-10
      = link_to t(".delete"), recipient_path(recipient), method: :delete,
        class: "btn btn-danger", data: {confirm: t(".delete_confirm")}

app/views/recipients/edit.html.slim
- provide :title, t(".title")
= link_to t(".back"), recipients_path
= render "form", recipient: @recipient

app/views/recipients/index.html.slim
- provide :title, t(".title")
.content
  .block
    .block-content
      .panel.panel-default
        .panel-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th = t ".email"
                  th = t ".bank_name"
                  th = t ".branch_name"
                  th = t ".account_type"
                  th = t ".account_number"
                  th = t ".recipent_name"
                  th = t ".currency"
                  th.text-center
                    = t ".action"

              tbody
                = render partial: "recipient", collection: @recipients