config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)" do
    get "help", to: "static_pages#help"
    devise_for :users
    resources :transfers do
      collection do
        post :fee
      end
    end
    resources :senders
    resources :recipients
    namespace :admin do
      resources :exchanges
      resources :transfers do
        collection do
          post :fee
        end
      end
      resources :high_transfers, only: %i[new create]
    end
  end
end

app/models/sender.rb
# == Schema Information
#
# Table name: senders
#
#  created_at    :datetime         not null
#  currency      :integer
#  id            :integer          not null, primary key
#  name          :string
#  name_katakana :string
#  phone         :string
#  updated_at    :datetime         not null
#  user_id       :integer
#  wechat_id     :string
#
# Indexes
#
#  index_senders_on_user_id  (user_id)
#

# Sender
class Sender < ApplicationRecord
  belongs_to :user
  has_one :transfer, dependent: :nullify
  validates :name, presence: true
  validate :must_have_phone_or_wechat

  enum country: %i[china japan]
  enum currency: %i[jpy cny]

  PERMITTED_ATTRIBUTES = %i[name phone wechat_id].freeze

  private

  def from_japan?
    return false unless below_kind?
    transfer.payment.uneeds_exchange.currency_from_id == 1
  end

  def from_china?
    transfer.payment.uneeds_exchange.currency_from_id == 2
  end

  def below_kind?
    transfer.kind == Transfer.kinds.keys.first
  end

  def must_have_phone_or_wechat
    if phone.blank? && wechat_id.blank?
      errors.add(:phone, I18n.t(".errors.messages.sender.phone_or_wechat_require"))
      errors.add(:wechat_id, I18n.t(".errors.messages.sender.phone_or_wechat_require"))
    end
  end
end

app/controllers/senders_controller.rb
# SendersController
class SendersController < ApplicationController
  def index
    @senders = current_user.senders.decorate
  end

  def edit
    sender
    support
  end

  def update
    if sender.update_attributes(sender_params)
      flash[:notice] = t ".success"
      redirect_to senders_path
    else
      support
      render :edit
    end
  end

  def destroy
    if sender.destroy
      flash[:notice] = t ".success"
    else
      flash[:alert] = t ".failure"
    end
    redirect_to senders_path
  end

  private

  def sender
    @sender = Sender.find params[:id]
  end

  def support
    @support = SenderSupport.new
  end

  def sender_params
    params.require(:sender).permit Sender::PERMITTED_ATTRIBUTES
  end
end

app/helpers/senders_helper.rb
module SendersHelper
  def country_options
    Sender.countries.keys.map do |country|
      [I18n.t("dictionary.#{country}"), country]
    end
  end
end

app/views/senders/_form.html.slim
= simple_form_for sender do |f|
  .panel.panel-default
    .panel-heading
      = t ".sender_info"
    .panel-body
      = f.input :name, label: t(".name")
      = f.input :phone, label: t(".phone")
      = f.input :wechat_id
      = f.input :currency, disabled: true, collection: currency_options,
        prompt: t(".choose_currency"), label: t(".currency")
  .col-lg-12.text-center
    = f.submit  t(".#{sender.new_record? ? :create : :update}"), class: "btn btn-primary"

app/views/senders/_sender.html.slim
tr
  td
    = sender.name
  td
    = sender.phone
  td
    = sender.wechat_id
  td
    = sender.decorated_currency
  td.text-center
    .btn-group.navbar-btn
      = link_to t(".edit"), edit_sender_path(sender), class: "btn btn-info"
    .btn-group.navbar-btn.ml-10
      = link_to t(".delete"), sender_path(sender), method: :delete,
        class: "btn btn-danger", data: {confirm: t(".delete_confirm")}

app/views/senders/edit.html.slim
- provide :title, t(".title")
= link_to t(".back"), senders_path
= render "form", sender: @sender, support: @support

app/views/senders/index.html.slim
- provide :title, t(".title")
.content
  .block
    .block-content
      .panel.panel-default
        .panel-body
          .table-responsive
            table.table.table-striped
              thead
                tr
                  th = t ".name"
                  th = t ".phone"
                  th = t ".wechat"
                  th = t ".currency"
                  th.text-center = t ".action"

              tbody
                = render partial: "sender", collection: @senders